[theme]
base = "dark"
primaryColor = "#00ffd0"
blueColor = "#00ffd0"
blueTextColor = "#fff"
font = "Catamaran,Arial,sans-serif"

[client]
showErrorDetails = true

[server]
enableCORS = false
enableXsrfProtection = false
headless = true
port = 8501

[logger]
level = "info"